import React, { useState, useEffect } from 'react';
import { IPresence,IChannel, createPresence } from '@yomo/presence';
import Head from 'next/head';
import styles from '@/styles/Chat.module.css';

interface Message {
    id: string;
    message: string;
  }
export default  function Chat ( ){
   


    const [messages, setMessages] = useState<Message[]>([]);
    const [newMessage, setNewMessage] = useState('');
    const [connected, setConnected] = useState(false);
   // const [channel, setChannel] = useState<IChannel>();
    const [presence, setPresence] = useState<any>();
    const [channel, setChannel] = useState<IChannel | null>(null);
    const [presenceClient, setPresenceClient] =
      useState<Promise<IPresence> | null>(null);

     
// create an instance.
useEffect(() => {
    let isSubscribed = true; // 用于跟踪组件挂载状态
  
    // 创建实时通讯客户端
    createPresence('https://prscd2.allegro.earth/v1', {
      publicKey: 'EIHHOvhgKGPWPJfFpjKQMmKcshZtSpa6ezwp2dp',
      id: 'user-client-id',
      debug: true,
      
    }).then(async (presence) => {
      console.log('Presence: ', presence);
      setConnected(true);
      try {
        const newChannel = await presence.joinChannel('chat-channel', { id: 'user-client-id' });
        if (isSubscribed) {
          setChannel(newChannel);
  
          // 订阅消息
          newChannel.subscribe('message', (payload, peerState) => {
            setMessages(prevMsgs => [...prevMsgs, { ...payload, peer: peerState }]);
          });
        }
      } catch (error) {
        console.error('Failed to join channel:', error);
      }
    });
  
    // 组件卸载时的清理函数
    return () => {
      isSubscribed = false;
      if (channel) {
        // 退出频道的方法
        channel.leave().catch(console.error);
      }
    };
  }, []);
  
const sendMessage = () => {
    if (channel && newMessage.trim() !== '') {
      const messageToSend: Message = {
        id: 'user-client-id',
        message: newMessage.trim(),
      };
      
      if (channel) {
        channel.broadcast('message', messageToSend);
// 更新自己的页面
setMessages(prevMsgs => [...prevMsgs, messageToSend]);
setNewMessage('');      }
    }
  };


    return(
        <>
        <Head>
        <title>Presence demo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main} style={{background: `url('./bg.svg')`}}>
        <div 
       // className={styles.chatbox}
        >
        <div>
            <div //className={styles.chatboxHistory}
            >
          {messages.map((msg, index) => (
            <p key={index}>
              {msg.message}
            </p>
          ))}</div>
          <div         // className={styles.chatboxInput}
>
          <textarea
         // className={styles.chatboxInput}
            type="text"
            value={newMessage}
            onChange={(e) => setNewMessage(e.target.value)}
            placeholder="输入消息..."
            onKeyDown={(e) => e.key === 'Enter' && sendMessage()}
            required
          />
          </div>
        </div>
        <button onClick={sendMessage}>发送</button>

      </div>
      </main>
      </>
    )
}